on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/zmkfirmware/zephyr-west-action:latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build firmware
        uses: zmkfirmware/zmk-build-actions@v3
        with:
          board: ergohaven
          extra_args: -DCONFIG_ZMK_STUDIO=y
